version: '3.9'
services:
  backend:
    container_name: backend
    build: ./backend
    ports:
      - 3001:3001
    command: npm run dev
    platform: linux/x86_64
    working_dir: /backend
    depends_on:
      - db
    environment:
      - APP_PORT=3001
      - DB_USER=root
      - DB_PASS=senha-mysql
      - DB_HOST=db
      - DB_PORT=3306
  db:
    image: mysql:8.0.21
    container_name: db
    platform: linux/x86_64
    ports:
      - 3306:3306
    environment:
      - APP_PORT=3001
      - DB_USER=root
      - DB_PASS=senha-mysql
      - DB_HOST=db
      - DB_PORT=3306
    restart: 'always'
    cap_add:
      - SYS_NICE